### ISSUE TITLE
Not able to find the files on the tree

### ISSUE THREAD

**Issue by vishesh-baghel** [vishesh-baghel/glide#19]
ERROR (probot): Error while fetching resource details for resource url: GET /repos/{owner}/{repo}/git/trees/{tree_sha}
ERROR (probot): Error occurred while fetching all files for vishesh-baghel/codespace-demo and installation id: 45484616
ERROR (HttpError): Not Found
    HttpError: Not Found
        at /home/vishesh.baghel/Documents/workspace/personal-projects/glide/node_modules/octokit/node_modules/@octokit/request/dist-node/index.js:124:21
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async sendRequestWithRetries (/home/vishesh.baghel/Documents/workspace/personal-projects/glide/node_modules/@octokit/auth-app/dist-node/index.js:398:12)
        at async requestWithGraphqlErrorHandling (/home/vishesh.baghel/Documents/workspace/personal-projects/glide/node_modules/octokit/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
        at async Job.doExecute (/home/vishesh.baghel/Documents/workspace/personal-projects/glide/node_modules/bottleneck/light.js:405:18)
status: 404
request: {
    method: "GET"
    url: "https://api.github.com/repos/vishesh-baghel/codespace-demo/git/trees/main?recursive=true"
    headers: {
      "accept": "application/vnd.github.v3+json",
      "user-agent": "octokit.js/3.1.2 octokit-core.js/5.0.2 Node.js/20.10.0 (linux; x64)",
      "authorization": "token [REDACTED]"
    }
    request: {}
}

**Comment by vishesh-baghel** [comment]
This error is happening because, the bot is not able to find 'main' branch which is currently set to default branch in the query parameters

**Comment by vishesh-baghel** [comment]
fixed this bug in PR branch for #16
