### ISSUE TITLE
Not able to calculate risk score due to error while sorting the commit list

### ISSUE THREAD

**Issue by vishesh-baghel** [vishesh-baghel/glide#24]
WARN (probot): Commit date not specified
ERROR (probot): a.date.getTime is not a function
    TypeError: a.date.getTime is not a function
        at /home/vishesh.baghel/Documents/workspace/personal-projects/glide/lib/services/riskScoreService.js:7:54
        at Array.sort (<anonymous>)
        at calculateRiskScore (/home/vishesh.baghel/Documents/workspace/personal-projects/glide/lib/services/riskScoreService.js:7:17)
        at /home/vishesh.baghel/Documents/workspace/personal-projects/glide/lib/services/repositoryService.js:129:98
        at Array.map (<anonymous>)
        at /home/vishesh.baghel/Documents/workspace/personal-projects/glide/lib/services/repositoryService.js:121:60
        at step (/home/vishesh.baghel/Documents/workspace/personal-projects/glide/lib/services/repositoryService.js:33:23)
        at Object.next (/home/vishesh.baghel/Documents/workspace/personal-projects/glide/lib/services/repositoryService.js:14:53)
        at fulfilled (/home/vishesh.baghel/Documents/workspace/personal-projects/glide/lib/services/repositoryService.js:5:58)

**Comment by vishesh-baghel** [comment]
Fixed in #16
